name: testing workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line command
        run: echo "hello eve"

  build-db:
    needs: build-app
    runs-on: windows-latest

    steps:
      - name: Run on Windows
        run: echo "hello windows"

  package:
    needs: [build-db,build-db]
    runs-on: windows-latest

    steps:
      - name: Package app
        run: echo "Packaging application"

###hello eve ggg