name: testing workflow-2

on:
    workflow_dispatch:

env:
    week_of_day: friday
    var_value: value1

jobs:
  mainjob:
    runs-on: ubuntu-latest

    env:
        Greeting : dear
        var_value: value2

    steps:
      - name: Greeting the person
        run: |
            echo "hello ${Greeting} today is ${week_of_day}"
            echo "value $var_value"
            echo "value ${{env.var_value}}""


