name: workflow testing

on:
    workflow_dispatch:

jobs:
    mainjob:
        runs-on: ubuntu-latest
        steps:
            - name: screat key
              run : |
                   echo "MY_TEST_PASS IS : $MY_TEST_PASS"




